export function Section2_Eula() {
    return (
        <div className="prose max-w-full text-sm cursor-default [--tw-prose-bullets:black]">

            <h3 title="HID Global Corporation on-premise software end user license agreement (version 07152020)">
                End User License Agreement
            </h3>

            <div className="overflow-auto h-96">

                <p className="mt-0 text-xs uppercase">
                    <strong>Important read carefully</strong> - These terms apply to software distributed by hid global corporation or an HID Global Corporation
                    affiliated entity (“Licensor”) for on-premise use, whether provided on a standalone basis or installed or embedded on hardware products.
                    By using, accessing, downloading or installing the software, you acknowledge that you have read this end user license agreement (“EULA”),
                    that you understand it, and that you agree to be bound by its terms. If you do not agree to the terms and conditions of this EULA,
                    you may not install or use the software.
                    If you are a channel partner, you agree to bind your end customers to terms substantially similar and no less restrictive to those set forth herein.
                </p>


                <h4>1. Definitions</h4>

                <p><strong>“Channel Partner”</strong> means an entity that Licensor has authorized as a “reseller” of the Software.</p>
                <p><strong>“Intellectual Property Rights”</strong> means worldwide common law and statutory rights associated with (a) patents and patent applications; (b) works of authorship, including mask work rights, copyrights, copyright applications, copyright registrations and “moral” rights; (c) the protection of trade and industrial secrets and confidential information; (d) all rights to registered and common law trademarks, trade names, trade dress, and service marks; and (e) other proprietary rights relating to intangible intellectual property (including but not limited to designs, design rights, source codes, proprietary material, know-how, ideas, concepts, methods, techniques, rights in databases and all other intellectual property rights and rights of a similar character whether registered or capable of registration).</p>
                <p><strong>“Licensee”</strong> means the end customer that has purchased the Software either directly from Licensor or through a Channel Partner.</p>
                <p><strong>“Perpetual”</strong> means the licensing business model whereby Licensee or Channel Partner, as applicable, pays Licensor a one-time license fee for use of the version of the Software, as originally delivered to Licensee, in perpetuity.</p>
                <p><strong>“Purchase Documents”</strong> means the invoice and/or other purchasing documentation or order acknowledgment issued by Licensor or Channel Partner.</p>
                <p><strong>“Software”</strong> means the software and corresponding licenses as more particularly described in the Purchase Documents, and any associated guides and manuals (<strong>“Documentation”</strong>) provided by Licensor hereunder.</p>
                <p><strong>“Subscription”</strong> means the business model whereby Licensee or Channel Partner, as applicable, pays Licensor a fee for use of the Software for a specified term.</p>

                <h4>2. Grant of License.</h4>
                <p>In consideration of payment of the applicable license fee and subject to compliance with the terms and conditions of this EULA, Licensor grants Licensee a non-exclusive, non-transferable, non-sublicensable, worldwide right to use the Software solely for Licensee’s internal business operations, and not for further resale. Licensee’s right to use the Software is expressly limited to the number of end users, workstations, servers or other such limitations as indicated by the Purchase Documents. Only object code, machine-readable versions of the Software are licensed to Licensee hereunder, and Licensee has no rights under this EULA to the source code versions of the Software. Licensee may use, reproduce and internally distribute the Software solely in connection with and as reasonably necessary for Licensee’s authorized use of the Software and for backup and archive purposes. Licensee may not make any other copies of the Software. Provided, however, that Licensee may not copy any Software that is installed, embedded or otherwise resident in any hardware products.</p>

                <h4>3. Restrictions.</h4>
                <p>The license rights granted in this EULA are subject to the following restrictions (except and only to the extent such restrictions are prohibited by applicable law):</p>

                <ul>
                    <li>3.1. Licensee may not sell, license, sublicense, lend, rent, lease, or otherwise transfer the Software to a third party. Provided, however, Licensee may make the Software available to a third party to operate the Software on behalf of Licensee, subject to the terms and conditions of this EULA, and provided that Licensee shall be fully liable for such third party’s compliance with the terms and conditions of this EULA. Licensee may not use the Software for time-sharing, outsourcing, service bureau, or managed service provider purposes, or otherwise make the Software available to third parties for their commercial purposes, unless expressly authorized in writing by Licensor.</li>
                    <li>3.2. Licensee acknowledges that the Software in source code form remains a confidential trade secret of Licensor and/or its third-party licensors. Licensee may not reverse engineer, decipher, decompile,  modify  or disassemble the Software or otherwise attempt to derive the source code of the Software, incorporate the Software in whole or in part in any other software or product, or develop derivative works of the Software or allow others to do so, or to attempt to do any of the foregoing.</li>
                    <li>3.3. Licensee shall not disclose or publish the results of any performance, functional, or other evaluation or benchmarking of the Software to any third party without the prior written consent of Licensor.</li>
                    <li>3.4. If the Software or hardware product uses a volume license key or other method to limit the volume of use of the product, Licensee shall not disable, bypass or otherwise circumvent the operation of such key or method.</li>
                </ul>

                <h4>4. Audit.</h4>
                <p>Licensor or its agent may at any time audit Licensee for the sole purpose of determining the number of active licenses in use by Licensee (“In Use Licenses”).  Where the In Use Licenses materially exceed the purchased licenses, Licensor shall either notify the Licensee who shall within 10 business days reduce the In Use Licenses to be consistent with the purchased licenses or submit an invoice to the Licensee or Channel Partner for payment for the licenses that exceed the number of purchased licenses.</p>

                <h4>5. Ownership.</h4>
                <p>The Software is licensed under the terms of this EULA, not sold. The Software and all authorized copies thereof, shall remain the exclusive property of Licensor, and shall not be used in any way other than as allowed by this EULA, and shall not be disclosed to any third party. Licensee acknowledges that, as between Licensor and Licensee, the Software and all Intellectual Property Rights with respect thereto, are and will at all times be the property of Licensor, even if Feedback is incorporated into current or subsequent versions of the Software.</p>

                <h4>6. Confidentiality and Feedback.</h4>
                <p>Licensor and Licensee acknowledge that each party may have access to certain of the other party’s confidential and proprietary information in connection with the Software and this EULA (the “Confidential Information”). Each party will take all reasonable precautions necessary to safeguard Confidential Information, including those taken by such party to protect its own confidential information of a similar nature. Each party will use the other party’s Confidential Information solely to fulfill the purposes of this EULA. Neither party will have any confidentiality obligation with respect to any portion of the Confidential Information that (i) it independently develops without reference to the other party’s Confidential Information, (ii) it lawfully obtains from a third party under no obligation of confidentiality or (iii) becomes available to the public other than as a result of its act or omission. Licensee may, from time to time, provide suggestions, comments or other feedback to Licensor with respect to the Software ("Feedback"). Licensee agrees that all Feedback is and shall be entirely voluntary. Licensor shall be free to disclose and use such Feedback as it sees fit, entirely without obligation of any kind to Licensee.</p>

                <h4>7. Limited Warranty and Disclaimers.</h4>

                <ul>
                    <li><strong>7.1 Limited Warranty. </strong>Licensor warrants that for a period of ninety (90) days from the earlier of the date the Software is delivered to Licensee (FCA Origin) or downloaded by Licensee (“Warranty Period”): (i) the media on which the Software is recorded will be free from material defects in materials and workmanship under normal use, and (ii) the Software will perform substantially in accordance with the then-current Documentation, provided that such Software is properly used by Licensee in accordance with such Documentation and this EULA. This limited warranty is VOID if failure of the Software is due to accident, negligence, abuse, improper installation or misuse of the Software.</li>
                    <li><strong>7.2 Remedies. </strong>Licensor’s sole and exclusive liability and Licensee’s sole and exclusive remedy under this limited warranty shall be to, at Licensor’s election, either: (a) replace of the media if defective, or (b) use commercially reasonable efforts to repair or replace the Software to make the Software perform substantially in accordance with the accompanying Documentation. In the event Licensor is unable to remedy the non-conformity and such non-conformity materially affects the functionality of the Software, Licensee may promptly terminate the license applicable to the non-conforming Software and return such Software and any applicable Documentation to Licensor or Channel Partner, as applicable. In such event, Licensee will receive a refund of the license fee received by Licensor with respect to such Software, less the value of use to date. The above remedies are available only if Licensor or Channel Partner are promptly notified in writing within the Warranty Period. Any replacement Software will be warranted for the remainder of the original Warranty Period, or for thirty (30) days, whichever is longer.</li>
                    <li><strong>7.3 Disclaimer of Warranties. </strong>
                        <p className="text-xs">EXCEPT AS EXPRESSLY STATED IN THIS EULA, THE SOFTWARE IS PROVIDED “AS IS.” TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAWS, LICENSOR (AND ITS LICENSORS) EXPRESSLY DISCLAIM ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NONINFRINGEMENT. LICENSOR DOES NOT WARRANT THAT THE SERVICES OR FUNCTIONS CONTAINED IN THE SOFTWARE WILL MEET LICENSEE'S REQUIREMENTS, OR THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT DEFECTS IN THE SOFTWARE WILL BE CORRECTED. FURTHERMORE, NEITHER LICENSOR (NOR ITS LICENSORS) WARRANT OR MAKE ANY REPRESENTATIONS AND DISCLAIMS ALL LIABILITY REGARDING ANY LOSS OF DATA OR LOSS OF USE OF DATA (INCLUDING PERSONAL DATA), THE PERFORMANCE OR THE RESULTS OF THE USE OF THE SOFTWARE IN TERMS OF THEIR CORRECTNESS, ACCURACY, RELIABILITY, OR OTHERWISE.  NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY LICENSOR OR ITS AUTHORIZED REPRESENTATIVE SHALL CREATE A WARRANTY OR IN ANY WAY INCREASE THE SCOPE OF THIS WARRANTY. THE FOREGOING LIMITATIONS AND EXCLUSIONS APPLY TO THE EXTENT PERMITTED BY APPLICABLE LAW IN LICENSEE’S OR CHANNEL PARTNER’S JURISDICTION. IF APPLICABLE LAW LIMITS THE APPLICATION OF THE PROVISIONS OF THIS SECTION, LICENSOR’S LIABILITY WILL BE LIMITED TO THE MAXIMUM EXTENT PERMISSIBLE.</p>
                    </li>
                </ul>

                <h4>8. Data Privacy and Security.</h4>
                <p>Licensee is solely responsible for: (i) use of the Software, including without limitation, installation, deployment, and management of the Software; (ii) use of the Software in compliance with all applicable laws; (iii) ensuring the security of all data collected, processed, stored, and maintained using the Software; and (iv) providing adequate notice and obtaining and maintaining valid consents from all of Licensee’s end users, as may be necessary under applicable law (including data protection or data processing laws and regulations), to process their personal data using the Software for Licensee’s intended purposes.</p>

                <h4>9. Limitation of Liability.</h4>
                <p className="text-xs">LICENSOR, ITS LICENSORS, AGENTS, AND SUPPLIERS SHALL NOT BE LIABLE WHATSOEVER FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOST PROFITS, DATA (INCLUDING PERSONAL DATA) OR LOSS OF USE, OR PROCUREMENT OF REPLACEMENT SOFTWARE, HOWEVER INCURRED BY THE LICENSEE OR ANY THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT, EVEN IF LICENSOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE AGGREGATE AND CUMULATIVE LIABILITY OF LICENSOR FOR DAMAGES UNDER THIS EULA SHALL NOT EXCEED THE AMOUNT OF THE FEES PAID BY LICENSEE FOR THE AFFECTED SOFTWARE DURING THE TWELVE (12) MONTH PERIOD IMMEDIATELY PRECEDING THE CLAIM GIVING RISE TO ANY LIABILITY.</p>

                <h4>10. Compliance with Laws and Export.</h4>
                <p>Licensee shall comply with all applicable laws, ordinances, rules and regulations, and shall obtain any and all permits, licenses, authorization, and/or certificates that may be required in any jurisdiction or any regulatory or administrative agency in connection with the sale, use and/or operations of Software, including any collection or use of personal data and/or personal information, as defined by applicable law.  Licensee shall comply fully with all international and national laws and regulations that apply to the Software and  to  Licensee’s  use  thereof,  including,  but  not  limited  to  the  U.S.  Export Administration Regulations and end user, end-use and destination restrictions issued by U.S. and other governments. Without limiting the generality of the foregoing, Licensee expressly agrees that it shall not, and shall cause its representatives to agree not to, export, directly or indirectly, re-export, divert, or transfer the Software or Documentation or any direct product thereof to any destination, company or person restricted or prohibited by U.S. laws or regulations or laws or regulations of any other applicable jurisdiction.</p>

                <h4>11. Third Party Components.</h4>
                <p>Licensee acknowledges that the Software may include incorporated third party software components or require the use of third party software programs (collectively, “Third Party Components”) including programs that are available under either their own license, or an open source or free software license (each a “Third Party License”). Third Party Licenses are typically found in a readme file in the Software or accompanying the Software and/or hardware. This EULA does not alter any rights or obligations Licensee may have under Third Party Licenses. Third Party Components are provided “AS IS” and notwithstanding anything to the contrary, the Disclaimer of Warranties and Limitation of Liability provisions of this EULA shall apply to Third Party Components.</p>

                <h4>12. U.S. Government Restricted Rights.</h4>
                <p>The Software is provided with "Restricted Rights". Use, duplication or disclosure by the U.S. Government is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the Rights in Technical Data and Computer Software clause at DFARS 252.227-7013 or subparagraphs (c)(1) and (2) of the Commercial Computer Software-Restricted Rights at 48 CFR 52.227-19, as applicable (and the successor clauses to any of the foregoing). The contractor/manufacturer is HID Global Corporation. All Software provided to the U.S. Government, including its civilian and military agencies, is commercial computer software that was developed at private expense prior to its provision to any U.S. Government entity.  Subject to any applicable regulations set out in the FAR or DFARS (and any superseding regulations), the Software is provided with the commercial license rights and restrictions described elsewhere in this EULA.  For Department of Defense agencies, the restrictions set forth in the "Technical Data - Commercial items" clause at DFARS 252.227-7015 (Nov 1995) shall also apply.</p>

                <h4>13. Procurement and Support of System.</h4>
                <p>Licensee is responsible for procuring, installing and maintaining the hardware or software infrastructure, including a suitable operating system environment (collectively the “System”), required for the proper operation of the Software. Licensee acknowledges that updates to the Software provided as part of any support or maintenance service provided by Licensor or Channel Partner may require modification or upgrades to certain components of the System in order to utilize such updates, and that Licensee is solely responsible for obtaining such software and hardware modification or upgrades from the applicable suppliers or manufacturers.</p>

                <h4>14. Term and Termination of License.</h4>
                <p>The term applicable to Licensee’s use of the Software shall be on a: (i) Subscription basis subject to payment of the applicable subscription fees for each term; or (ii) Perpetual basis, as indicated in the Purchase Documents. Licensor reserves the right to terminate this EULA and Licensee’s corresponding right to use the Software in the event Licensee breaches a material obligation under this EULA and fails to cure such breach within thirty (30) days after Licensor sends written notice describing the breach if such breach is capable of being cured, or immediately if the breach is not capable of being cured. Upon any termination of this EULA, or if Licensee should discontinue use of the Software or give up personal use and control of the computers or other  hardware  on  which  the  Software  is  installed,  Licensee  shall  destroy  all  copies  of  the  Software and any related Documentation in any form. The Sections of this EULA which contemplate performance or observance subsequent to termination or expiration of this EULA, or which by their nature are intended to survive termination or expiration of this EULA shall so survive termination or expiration and continue in full force and effect.</p>

                <h4>15. General.</h4>
                <ul>
                    <li><strong>15.1. </strong>Licensee may not assign this EULA or any of its right hereunder without the prior written consent of Licensor. Any attempt by the Licensee to assign any rights, duties or obligations, which arise under this EULA without such permission shall be void.</li>
                    <li><strong>15.2. </strong>Any waiver or forbearance shall be valid only if in writing. No waiver by a party of any default shall operate as a waiver of any other default or of the same default on a future occasion. No delay, course of dealing or omission on the part of one party in exercising any right or remedy shall operate as a waiver thereof, and no single or partial exercise by such party of any right or remedy shall preclude any other or further exercise thereof or the exercise of any other right or remedy.</li>
                    <li><strong>15.3. </strong>If any provision or provisions of this EULA shall be held to be invalid, illegal or unenforceable, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired thereby, provided such provisions still express the intent of the parties. If the intent of the parties cannot be preserved, the EULA shall either be renegotiated or rendered null and void.</li>
                    <li><strong>15.4. </strong>No remedy conferred by this EULA is intended to be exclusive of any remedy, except as expressly provided, and each and every remedy shall be cumulative and in addition to every other remedy given under this EULA or now or in the future existing in law or in equity or by statute or otherwise.</li>
                    <li><strong>15.5. </strong>This EULA is not made for the benefit of, nor shall any of its provisions be enforceable by any person other than Licensor, Licensee and their respective successors and permitted assignees.</li>
                    <li><strong>15.6. </strong>This EULA shall be construed and interpreted in accordance with the laws of the State of Texas, USA. Any action, suit or proceeding relating to this EULA may be brought in the appropriate the appropriate court located in Travis County, Texas and each party hereby consents to such jurisdiction. The provisions of the United Nations Convention on Contracts for the International Sale of Goods will not apply to this EULA or any order issued hereunder.</li>
                    <li><strong>15.7. </strong>Unless otherwise agreed in writing by the parties, this EULA constitutes the entire understanding and agreement between the parties hereto with respect to the subject matter of this EULA and merges and supersedes all prior communications, understanding and agreements, written or oral. Any modifications to this EULA must be in writing and signed by a proper and duly authorized representative of the party to be bound thereby. Licensor shall not be bound by any differing or inconsistent terms contained in any order form, purchase order or other form issued by Licensee.</li>
                </ul>
            </div>

        </div>
    );
}
